local o = vim.opt
o.number = true
o.relativenumber = true
o.signcolumn = "yes"
o.clipboard = "unnamedplus"
o.ignorecase = true
o.smartcase = true
o.expandtab = true
o.shiftwidth = 2
o.tabstop = 2
o.termguicolors = true
o.updatetime = 200
o.timeoutlen = 400
